//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Tripp\'n Technology, LLC.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Tripp\'n Technology, LLC. 2018")]
[assembly: System.Reflection.AssemblyFileVersion("1.6.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.6.0.0-1812142237")]
[assembly: System.Reflection.AssemblyTitle("TNT Utilities")]
[assembly: System.Reflection.AssemblyVersion("1.6.0.0")]
[assembly: System.Reflection.AssemblyDescription("TNT Utilities")]
[assembly: System.Reflection.AssemblyProduct("TNT Utilities")]


